from gpiozero import LED, Button
from time import sleep
button = Button(24)
led = LED(23)
while True:
    if button.wait_for_active():
        for i in range(3):
            led.on()
            sleep(1)
            led.off()
            sleep(1)
            led.on()
            sleep(1)
            led.off()
            sleep(1)
            led.on()
            sleep(1)
            led.off()
            sleep(0.3)
            led.on()
            sleep(0.3)
            led.off()
            sleep(0.3)
            led.on()
            sleep(0.3)
            led.off()
            sleep(0.3)
            led.on()
            sleep(0.3)
            led.off()
            sleep(0.3)
            led.on()
            sleep(1)
            led.off()
            sleep(1)
            led.on()
            sleep(1)
            led.off()
            sleep(1)
            led.on()
            sleep(1)
            led.off()
            sleep(1)
